### ISSUE TITLE
Attestation Results using CoRIM schema

### ISSUE THREAD

**Issue by thomas-fossati** [CCC-Attestation/meetings#19]
_Proposal received from @nedmsmith_

### CoRIM Attestation Results (CAR)

The general objective is to show how CoRIM schema can be used to build an attestation results structure that serializes the ACCEPTABLE CLAIMS SET in a straightforward way.

Verifier provided claims, such as AR4SI summarization, follows the endorsement pattern.

I have example use cases that walk-through construction of the ACCEPTABLE CLAIMS SET to bring the audience along toward a logical conclusion that the Verifier generated claims follow the endorsement pattern (i.e., can reuse CoRIM schema).

It might make sense to structure the talk as a comparison between [EAR](https://datatracker.ietf.org/doc/draft-fv-rats-ear/)/CAR. They are not that different.

**Comment by gkostal** [comment]
@nedmsmith - thank you for presenting over a series of three meeting in Nov-23, Dec-23, Jan-24.

@thomas-fossati - Ned presented and the slides are uploaded.  Can we close this issue now?
