### ISSUE TITLE
Common ABI for attestation in the Linux kernel

### ISSUE THREAD

**Issue by thomas-fossati** [CCC-Attestation/meetings#20]
"configfs TSM" is a [recently published](https://lore.kernel.org/all/169570181657.596431.6178773442587231200.stgit@dwillia2-xfh.jf.intel.com/T/#m6388bb0eff53568a47b8cae52a4a948cdcde4a1f) set of patches to the Linux kernel (targeting v6.7, IIUC) that provide a common interface for confidential guest VMs to retrieve attestation reports from the host TVM.

"configfs TSM" aims at creating a common framework that supersedes the current per-vendor ioctl-based solutions.

It’d be nice if someone from the linux-coco community could come to one of the SIG meetings and present:

* use cases
* the framework
* the ABI (interface, semantics), and
* discuss Implementation choices (e.g., why configfs was preferred over sysfs)

**Comment by thomas-fossati** [comment]
@sameo would you, or someone else from linux-coco community able to take this?

**Comment by wenhuizhang** [comment]
Hopefully, this API could consider both Intel RTMR backend and AMD vTPM backend

**Comment by thomas-fossati** [comment]
As discussed with @sameo, to be scheduled post LPC'23, i.e., after the 15th of November.

**Comment by thomas-fossati** [comment]
Scheduled for the 19th December call.

**Comment by sameo** [comment]
@jdbeaney I should be able to give an overview, yes.

**Comment by gkostal** [comment]
@sameo - thank you for presenting this topic on 1/16/24.  

@thomas-fossati - Sam presented on 1/16/24 and the [slides](https://github.com/CCC-Attestation/meetings/blob/main/materials/SamuelOrtiz_LinuxKernelAttestationABI.pdf) are uploaded.  Can we close this issue?
