### ISSUE TITLE
Remote Attestation and Workload Identity

### ISSUE THREAD

**Issue by TheBankster** [CCC-Attestation/meetings#41]
The evolving regulatory environment coupled with a steady stream of high-profile and costly breaches is leading enterprises to focus on the mechanisms of securing and governing deployed workloads. An increasingly pressing need in enterprise IT is being able to securely authenticate workloads to each other and controlling which workloads can access what data. This need has been recognized and a variety of approaches are competing for adoption and viability, such as the SPIFFE/SPIRE architecture, the WIMSE working group at the IETF and others.

While it is quite clear that for the foreseeable future this need is not going to be met by Confidential Computing alone, Confidential Computing does offer some of the most desirable security features related to workload identification and isolation that eclipse other approaches. Confidential Computing will need to evolve to fit within and ideally serve as the North Star of workload identity as it becomes a foundational pillar of trustworthy enterprise computing. Remote Attestation plays a key role in workload identification and it is thus critically important to architect it in a way that best fits within the workload identity space.

The workload identity problem space can be defined by the following set of key scenarios and requirements:

	1. Any two workloads, WA and WB, should be able to obtain identities WIA and WIB, use these identities to obtain credentials WCA and WCB authenticate to each other. The identities, credentials and authentication/authorization mechanisms in question must all be portable and standards based, and capable of supporting either transport-level or application-level security.
	2. There has to exist a strong link connecting an identity of a workload and its lineage, such that one workload cannot impersonate another when obtaining credentials.
		a. In case of workloads developed in-house, integration of workload identity with CI/CD mechanisms is highly desirable
		b. In case of managed workloads or workloads obtained from trusted sources, other forms of lineage establishment can be used, with automation is accountability remaining key features
		c. Both code identity and the configuration/environment in which the code is deployed are important in workload identity establishment; the environment may include attributes such as whether the code is deployed in test or production, what physical location the computation takes place in, and others.
	3. The credentials, once issued to a workload, must be strongly bound to the workload’s instance in order to minimize the chances of a credential being leaked and repurposed.
		a. For this to work, the use of bearer tokens must be strongly discouraged
		b. Obtaining cryptographic keys for identity or credential establishment from secret stores is less desirable than having each workload generate and certify its own keys, but may be unavoidable in some environments
	4. The workloads can take a wide variety of shapes and be deployed in a variety of environments, such as:
		a. Regular virtual machines, including but not limited to confidential virtual machines
		b. Various incarnations of container-based workloads (in AWS that might include Fargate, EKS and ECS)
		c. Confidential Computing enclaves
		d. Serverless computing
		e. Managed services including SaaS offerings
	5. Workloads might be standalone or compound (compound workloads being those consisting of multiple components that share the same lifetime from deployment through to decommissioning and potentially spanning devices or having components residing on the same physical device), with compound workloads having multiple credentials issued to them, e.g., for purposes of inbound, outbound and internecine (component-to-component) authentication
	6. Workloads might be short- or long-lived with different requirements applied to each kind:
		a. For short-lived workloads, it may be important to issue credentials quickly so as not to introduce performance and reliability issues related to multiple and/or expensive round-trips involved in credential issuance
		b. For long-lived workloads, the lifetime of a workload is likely to exceed that of the credentials issued to it, requiring ability to renew and/or revoke credentials in response to governance requirements and/or emerging threats without compromising overall system reliability
	7. Governance of workload identities and credentials must include some of the following capabilities:
		a. Maintaining control over and a history of all policies involved in issuing and evaluating identities and credentials
		b. Ability to identify and isolate vulnerable workloads in production quickly, such as when new threats are discovered or new attacks detected
		
So what does all that mean to Confidential Computing style Remote Attestation?

	1. There has to exist a set of easy to adopt mechanisms that tie Remote Attestation with workload credential issuance, where the issued Workload Credentials are interoperable with those utilized by the rest of the Workload Identity ecosystem. As such the interplay between RATS-style Remote Attestation and industry standard identity providers and credential issuance mechanisms has to be investigated, documented and supported — across all Verifier implementations.
	2. While Remote Attestation contains the information needed to establish the lineage of an attesting workload, the mechanisms for extending this lineage to issued workload credentials need to be defined.
	3. Workloads ought to be able to both generate and certify their own keys, or obtain keys/credentials from secret key stores. The role of Remote Attestation in either of those cases has to be precisely defined and widely supported.
	4. Remote Attestation-based workload credential issuance has to be supported on a wide variety of computing platforms, including those that do not strictly follow Confidential Computing “hardware-based” tenets, such as AWS Nitro and all types of compute including serverless and managed workloads.
	5. Remote Attestation mechanisms for compound workloads must be defined, including both compound workloads deployed on a single device (e.g., CPU + GPU + Smart NIC) and multiple devices (K8S pods/services, auto-scaling compute instances behind a load balancer, compound workloads sharing a lifetime, etc.)
	6. Credential issuance, re-issuance and revocation mechanisms may need to be optimized differently for short-lived and long-lived workloads.
	7. Governance of remote attestation  and workloads themselves must follow the governance patterns being defined by (and in collaboration with) the Governance SIG.

**Comment by thomas-fossati** [comment]
@TheBankster, clarifying question: is this intended as the charter of work or as the content itself that we want to put in https://github.com/CCC-Attestation/meetings/blob/main/musings/workload-identity.md ?

**Comment by TheBankster** [comment]
I am guessing yes?

**Comment by thomas-fossati** [comment]
> I am guessing yes?

That doesn't really clarify though 😆

**Comment by TheBankster** [comment]
I’ll move it to the .md file and close the issue.

**Comment by TheBankster** [comment]
Created the .md file to capture the discussion
